### ISSUE TITLE
Binning to square pixels and bad file names

### ISSUE THREAD

**Issue by MarkDurre** [kcwidev/kderp#11]
Do you have software (or can recommend) that can re-bin the rectangular pixels in the data cube to square. I am aware of the routine "ifsr_kcwiresample" from David Rupke, and I am in the process of modifying it to work on all redux files, like the rest of the pipeline (i.e. I'm making "kcwi_stage9bin"). Are there any gotchas that you might know of?

Also, I have found that the pipeline doesn't like spaces in the folder name, e.g.
```
KCWI_WRITE_PPAR      [INFO 1 ] kb180509_00020_mbias.ppar written in directory /Volumes/Data (External)/OneDrive - Swinburne University/KCWI/KCWI_Raw/180509/redux/
IDL> kcwi_stage1
% Compiled module: KCWI_STAGE1.
KCWI_VERIFY_DIRS     [ERROR  ] cannot access raw image dir: /Volumes/Data/
KCWI_STAGE1          [ERROR  ] Directory error, returning
```
Can this be fixed?

**Comment by kcwidev** [comment]
Hi,

Please use the official version of the pipeline that is linked on the front page.

The only issue with re-sampling the data cubes that I know of, is to be sure
that flux is conserved.  You may also want to be careful with the wavelengths
if you want to combine cubes from different configurations.

There are no plans (nor support) for changing the pipeline to handle spaces
in names.  I suggest using a link, perhaps?

**Comment by MarkDurre** [comment]
Unfortunately, links don’t work. Kcwi_stage1 still tries to use the “true” name.

Dr. Mark Durré
Centre for Astrophysics and Supercomputing
Swinburne University of Technology
PO Box 218, Hawthorn
Victoria 3122, Australia
Email: mdurre@swin.edu.au<mailto:mdurre@swin.edu.au>
