### ISSUE TITLE
Sky subtraction question.

### ISSUE THREAD

**Issue by fdeugenio** [kcwidev/kderp#9]
I am wondering whether the sky subtraction can be done by using the whole IFU to create a master spectrum.

**Comment by kcwidev** [comment]
That is exactly what the latest release of the pipeline does.  It models the sky by collecting points as a function of wavelength over the entire IFU, does a 1-sigma rejection, and then fits the result with b-splines to produce a sky spectrum model, which is then replicated over the entire IFU.  If there are non-sky pixels that dominate over certain wavelengths, then an over-subtraction will result.  If there are still good sky regions, the object pixels can be masked (see the AAAREADME for details) and these will not be used.  If an object fills the IFU, then a separate sky observation will be required and can be used as the model to subtract from the IFU-filling object.
